import { NextResponse } from "next/server"

const FIRST_NAMES = [
  "Aaliyah",
  "Aaron",
  "Abigail",
  "Adam",
  "Adrian",
  "Aiden",
  "Alex",
  "Alexa",
  "Alexander",
  "Alice",
  "Alicia",
  "Alina",
  "Amelia",
  "Amir",
  "Anna",
  "Anthony",
  "Aria",
  "Ava",
  "Benjamin",
  "Bianca",
  "Caleb",
  "Camila",
  "Charlotte",
  "Chloe",
  "Christopher",
  "Clara",
  "Daniel",
  "David",
  "Dylan",
  "Eleanor",
  "Elena",
  "Eli",
  "Elijah",
  "Elizabeth",
  "Ella",
  "Emily",
  "Emma",
  "Ethan",
  "Eva",
  "Evelyn",
  "Gabriel",
  "Grace",
  "Hannah",
  "Harper",
  "Hazel",
  "Henry",
  "Isaac",
  "Isabella",
  "Jack",
  "Jackson",
  "Jacob",
  "James",
  "Jasmine",
  "Joseph",
  "Joshua",
  "Julian",
  "Layla",
  "Leah",
  "Leo",
  "Liam",
  "Lila",
  "Lillian",
  "Lily",
  "Logan",
  "Lucas",
  "Lucy",
  "Luke",
  "Luna",
  "Madeline",
  "Mason",
  "Maya",
  "Mia",
  "Michael",
  "Mila",
  "Nathan",
  "Noah",
  "Nora",
  "Oliver",
  "Olivia",
  "Owen",
  "Penelope",
  "Riley",
  "Samuel",
  "Scarlett",
  "Sebastian",
  "Sofia",
  "Sophia",
  "Stella",
  "Theodore",
  "Violet",
  "William",
  "Zoe",
] as const

const MAX_RESULTS = 12
const SEARCH_DELAY_MS = 1000

export const GET = async (req: Request) => {
  const url = new URL(req.url)
  const search = url.searchParams.get("q")?.trim().toLowerCase() ?? ""

  await new Promise((resolve) => setTimeout(resolve, SEARCH_DELAY_MS))

  const names = search
    ? FIRST_NAMES.filter((name) => name.toLowerCase().includes(search)).slice(0, MAX_RESULTS)
    : FIRST_NAMES.slice(0, MAX_RESULTS)

  return NextResponse.json(
    {
      items: names,
      total: names.length,
      query: search,
    },
    { status: 200 },
  )
}
